### ISSUE TITLE
random assets fetched

### ISSUE THREAD

**Issue by sultan-710** [oncyberio/factory#30]
Hi oncyber, i have an issue with fetching my assets from polygon network when i try to add artwork into my oncyber space, everytime i try to get my all assets from my opensea account and my wallet i just get random number like 50, 100 sometimes 350 assets not more then that, accutally i have more then 2021 items in my wallet so idk why its not fetching my all assets at once. Plz help 

Thank you

![350assets](https://user-images.githubusercontent.com/73881369/150381575-e2763d46-c603-4019-b747-beadc1c9e707.png)
![100assets](https://user-images.githubusercontent.com/73881369/150381587-afaa3f69-e2b4-496c-b15d-591881dc8b52.png)

**Comment by julesGoullee** [comment]
@rayanoncyber
